### ISSUE TITLE
How can I get an telegram bot id? 

### ISSUE THREAD

**Issue by sheh1000** [lebe-dev/zabbix-telegram#2]
I need to get an user id. I read the FAQ where you explained that I should send message to bot. But I don't know bot id. How can I send message to him?

**Comment by lebe-dev** [comment]
bot id doesn't required. send message to bot name from desktop\web\mobile client

yes, this combination is not comfortable. i'll fix it for next release

**Comment by sheh1000** [comment]
Solution for people who will ask the same question.

**pip install python-telegram-bot**
```
import telegram
bot = telegram.Bot(token='XXXXXXXXX:AAFrRFIlRl4dujY7fJz2DXlQD6SpN9F-V8g')

# now user should send any message to your bot (we still don't know user id here)

# this line will show user id after bot will receive a message
print bot.getUpdates()[-1].message.chat_id
```

**Comment by lebe-dev** [comment]
thanks for your contribution, i don't have enough free time now, i'll check it later

**Comment by lebe-dev** [comment]
thanks again :) i tested your solition and updated README file
